# Site settings
title: K-blog!
email: kevinks.et@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "k-blog.github.io" # the base hostname & protocol for your site
twitter_username: shadowcomer
github_username: shadowcomer

# Build settings
markdown: kramdown
